---
- name: Установка базовых пакетов и Docker
  hosts: all
  become: true

  tasks:
    - name: Обновление списка пакетов apt
      apt:
        update_cache: yes

    - name: Установка базовых пакетов
      apt:
        name:
          - git
          - curl
          - wget
          - unzip
          - python3-pip
          - python3-dev
          - build-essential
          - libssl-dev
          - libffi-dev
        state: present

    - name: Установка Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present

    - name: Добавление ключа GPG для официального репозитория Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Добавление репозитория Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Установка пакета Docker
      apt:
        name: docker-ce
        state: present

    - name: Добавление пользователя в группу docker
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Перезапуск службы Docker
      service:
        name: docker
        state: restarted

