---
- name: Install base packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
   - git
   - curl
   - wget
   - unzip
   - python3-pip
   - python3-dev
   - build-essential
   - libssl-dev
   - libffi-dev

